const placesData = [
  { hebrew: "חשבונאות", english: "accounting" },
  { hebrew: "שדה תעופה", english: "airport" },
  { hebrew: "פארק השעשועים", english: "amusement_park" },
  { hebrew: "גלריית אמנות", english: "art_gallery" },
  { hebrew: "כספומט", english: "atm" },
  { hebrew: "מאפיה", english: "bakery" },
  { hebrew: "בנק", english: "bank" },
  { hebrew: "בר", english: "bar" },
  { hebrew: "באולינג", english: "bowling_alley" },
  { hebrew: "תחנת אוטובוס", english: "bus_station" },
  { hebrew: "בית קפה", english: "cafe" },
  { hebrew: "השכרת רכב", english: "car_rental" },
  { hebrew: "מוסך רכב", english: "car_repair" },
  { hebrew: "שטיפת מכוניות", english: "car_wash" },
  { hebrew: "בית קברות", english: "cemetery" },
  { hebrew: "חנות בגדים", english: "clothing_store" },
  { hebrew: "חנות נוחות", english: "convenience_store" },
  { hebrew: "כלבו", english: "department_store" },
  { hebrew: "בית מרקחת", english: "drugstore" },
  { hebrew: "שגרירות", english: "embassy" },
  { hebrew: "תחנת דלק", english: "gas_station" },
  { hebrew: "חדר כושר", english: "gym" },
  { hebrew: "טיפוח שיער", english: "hair_care" },
  { hebrew: "בית חולים", english: "hospital" },
  { hebrew: "ספריה", english: "library" },
  { hebrew: "תחנת רכבת קלה", english: "light_rail_station" },
  { hebrew: "חנות משקאות", english: "liquor_store" },
  { hebrew: "לינה", english: "lodging" },
  { hebrew: "ארוחה טייק אווי", english: "meal_takeaway" },
  { hebrew: "אולם קולנוע", english: "movie_theater" },
  { hebrew: "מוזיאון", english: "museum" },
  { hebrew: "מועדון לילה", english: "night_club" },
  { hebrew: "פארק", english: "park" },
  { hebrew: "חניה", english: "parking" },
  { hebrew: "חנות לחיות מחמד", english: "pet_store" },
  { hebrew: "בית מרקחת", english: "pharmacy" },
  { hebrew: "פיזיותרפיסט", english: "physiotherapist" },
  { hebrew: "דואר", english: "post_office" },
  { hebrew: "מסעדה", english: "restaurant" },
  { hebrew: "בית ספר", english: "school" },
  { hebrew: "בית ספר תיכון", english: "secondary_school" },
  { hebrew: "קניון", english: "shopping_mall" },
  { hebrew: "ספא", english: "spa" },
  { hebrew: "אצטדיון", english: "stadium" },
  { hebrew: "חנות", english: "store" },
  { hebrew: "תחנת רכבת תחתית", english: "subway_station" },
  { hebrew: "סופרמרקט", english: "supermarket" },
  { hebrew: "בית כנסת", english: "synagogue" },
  { hebrew: "תחנת מוניות", english: "taxi_stand" },
  { hebrew: "מוקד תיירות", english: "tourist_attraction" },
  { hebrew: "תחנת רכבת", english: "train_station" },
  { hebrew: "תחנת תחבורה", english: "transit_station" },
  { hebrew: "אוניברסיטה", english: "university" },
  { hebrew: "גן חיות", english: "zoo" },
];

export default placesData;
